#! /usr/bin/env python3
import urwid as u
import sys
from tutils import *

KEYS = {"1":0,"2":1,"3":2,"4":3,"5":4,"6":5,"7":6,"8":7,"9":8,"0":9,"!":10,"@":11,"#":12,"$":13,"%":14,"^":15,"&":16,"*":17,"(":18,")":19}

activities = load()
SELECTED = None if len(activities) == 0 else activities[0].name
ON = False

def args_handler(args):

    if args[0].lower() in ("add","a"):
        name = args[1]
        activities.add(name)
        save(activities)

    if args[0].lower() in ("del","d"):
        name = args[1]
        activities.delete(name)
        save(activities)

    if args[0].lower() == "log":
        name = args[1]
        print(activities.getlog(name))

    if args[0].lower() == "logs":
        print(activities.getlogs())

    if args[0].lower() == "today":
        name = args[1]
        print(activities.todays_log(name))

    if args[0].lower() == "list":
        for name in activities.get_all_names():
            print(name)

    if args[0].lower() == "flush":
        activities.flush()
        save(activities)

    if args[0].lower() in ("select","sel"):
        name = args[1]
        activities.select(name)
        save(activities)

    if args[0].lower() == "clean":
        name = args[1]
        if name == "all": activities.clean_all_logs()
        else: activities.clean_log(name)
        save(activities)

def input_handler(key):
    global SELECTED, ON

    if key == "q": raise u.ExitMainLoop()

    if key == "s":
        if not ON:
            ON = True
            activities.activate(SELECTED)
            timer(_loop=loop,_data="")
        elif ON:
            ON = False
            activities.deactivate()
            save(activities)
            text.set_text(f"Finished: {activities.todays_log(SELECTED)}")

    if key == "l" and not ON:
        text.set_text(f"{SELECTED} Log:\n\n{activities.getlog(SELECTED)}")

    if key == "c" and not ON:
        activities.clean_todays_log(SELECTED)
        save(activities)
        text.set_text(f"Today's {SELECTED} Log Cleared")

    if key == "C" and not ON:
        activities.clean_log(SELECTED)
        save(activities)
        text.set_text(f"{SELECTED}'s All Logs Cleared")

    if key == "D" and not ON:
        activities.delete(SELECTED)
        save(activities)
        text.set_text(f"{SELECTED} Deleted from Activities")

    if key in KEYS and not ON:
        key = KEYS[key]
        if key < len(activities):
            SELECTED = activities[key].name
            text.set_text(f"Selected: {SELECTED}")

def timer(_loop,_data):
    if ON:
        text.set_text(
            f"{SELECTED} is now active!\n\n {activities.todays_log(SELECTED)}"
        )
        loop.set_alarm_in(1,timer)

text = u.Text(f"Selected: {SELECTED}","center")
fill = u.Filler(text)

if len(sys.argv) > 1:
    args_handler(sys.argv[1:])
else:
    if SELECTED is None: print("No activities found. Exiting..."); exit()

    try: loop = u.MainLoop(fill,unhandled_input=input_handler); loop.run()
    except KeyboardInterrupt: print("Exiting...")
